### ISSUE TITLE
Segments (colors) do not appear in the Progress Bar on version 16.22.5+

### ISSUE THREAD

**Issue by hero3210** [Galactic-Dev/iSponsorBlock#35] opened 2021-11-02 15:16 UTC
**Description of the bug**
Segments (or colors) do not appear in the Progress Bar on versions 16.22.5+ (the issue is still present on the latest version 16.43.2).
it works fine and appears on version 16.20.5 and below.

**To Reproduce**
1. Download [Youtube 16.22.5](https://apps.apple.com/us/app/youtube-watch-listen-stream/id544007664) or later.
2. install iSponsorBlock
3. watch a video with sponsors ([example](https://www.youtube.com/watch?v=GHwpC81hwJ4)), you will not see the green color in the video Progress Bar (the tweak functions normally aside from the color issue).

**Expected behavior**
iSponsorBlock segment colors should appear in the Progress Bar.

**Screenshots**
- [v16.20.5](https://imgur.com/FW8xWF2) (working normally).
- [v16.22.5+](https://imgur.com/fr6eSpo) (not appearing anymore - screenshot is from the latest version 16.43.2).

**Please complete the following information:**
 - iOS Version: [e.g. 14.3]
 - Device: [e.g. iPhone X]
 - YouTube Version [e.g. 16.22.5]
 - iSponsorBlock Version [e.g. 1.0-10]

**Additional context**
None. Thanks for making this amazing port & letting me know about the project.

**Comment by Galactic-Dev** [comment] 2021-11-26 16:58
This should be fixed in the latest beta available on my discord server. If you want to test it you can find it in the iSponsorBlock server. Here is a link https://discord.gg/EACxr6rGvZ

**Closed by Galactic-Dev** 2021-11-26 16:58 UTC
Labels: bug

**Comment by suyashbansal** [comment] 2022-01-30 14:48
The issue is reoccurring in version 17.03.2 of YouTube.

**Comment by Galactic-Dev** [comment] 2022-01-30 17:31
> The issue is reoccurring in version 17.03.2 of YouTube.

This is now fixed in the latest isb version (1.0-12)
