### ISSUE TITLE
Manual Skip Segment doesn’t disappear when switching video

### ISSUE THREAD

**Issue by Terrain2** [Galactic-Dev/iSponsorBlock#21] opened 2021-03-13 22:03 UTC
If you switch videos during a Manual Skip segment (either through the video next/previous buttons or through suggested videos), the prompt still appears to skip it on the new video - clicking skip causes the app to crash

![Cr4shed showing the culprit as iSponsorBlock.dylib, Reason is below in text](https://user-images.githubusercontent.com/37938646/111050970-15a02900-8450-11eb-851f-037338513c13.jpeg)

*** -[__NSArrayM objectAtIndexedSubscript:]: index 18446744073709551615 beyond bounds [0 .. 1]

that's a pretty high index

the crash also [locked my app until reboot](https://discord.com/channels/603643120093233162/745806789945196654/820412557357350962) once, but i can't reproduce that

**Comment by Galactic-Dev** [comment] 2021-03-13 23:15
Thanks, I'll look into it. And the high index is from trying to get a -1 index of the array which is the cause of the crash.

**Comment by Galactic-Dev** [comment] 2021-04-05 04:37
fixed in 1.0-8

**Closed by Galactic-Dev** 2021-04-05 04:37 UTC
Labels: bug
